import mongoose from "mongoose";
import Mission from "./model/Mission.js";

await mongoose.connect(
  "mongodb://mongo:lmIwBZZfLxYhnfBZNDQURuLHgjDzukva@ballast.proxy.rlwy.net:46701"
);
await Mission.insertMany([
  {
    title: "Win 1 game",
    type: "daily",
    goal: 1,
    statKey: "gamesWon",
    rewardXp: 100,
    rewardCoins: 50,
  },
  {
    title: "Play 2 games",
    type: "daily",
    goal: 2,
    statKey: "gamesPlayed",
    rewardXp: 80,
    rewardCoins: 30,
  },
  {
    title: "Capture 5 pieces",
    type: "daily",
    goal: 5,
    statKey: "totalCaptures",
    rewardXp: 120,
    rewardCoins: 50,
  },
  {
    title: "Make 1 king",
    type: "daily",
    goal: 1,
    statKey: "kingsMade",
    rewardXp: 100,
    rewardCoins: 40,
  },
  {
    title: "Perform a double capture",
    type: "daily",
    goal: 1,
    statKey: "multiCaptures.double",
    rewardXp: 150,
    rewardCoins: 60,
  },
  {
    title: "Use backward capture",
    type: "daily",
    goal: 1,
    statKey: "usedBackwardCapture",
    rewardXp: 120,
    rewardCoins: 40,
  },
  {
    title: "Win with opponent having 5+ pieces",
    type: "daily",
    goal: 1,
    statKey: "winWithEnemyPieces5Plus",
    rewardXp: 200,
    rewardCoins: 80,
  },
  {
    title: "Play with 3 different players",
    type: "daily",
    goal: 3,
    statKey: "distinctOpponentsToday",
    rewardXp: 180,
    rewardCoins: 75,
  },
  {
    title: "Play 50 games",
    type: "reach",
    goal: 50,
    statKey: "gamesPlayed",
    rewardXp: 500,
    rewardCoins: 300,
  },
  {
    title: "Win 20 games",
    type: "reach",
    goal: 20,
    statKey: "gamesWon",
    rewardXp: 600,
    rewardCoins: 250,
  },
  {
    title: "Make 25 kings",
    type: "reach",
    goal: 25,
    statKey: "kingsMade",
    rewardXp: 700,
    rewardCoins: 300,
  },
  {
    title: "Perform 10 triple captures",
    type: "reach",
    goal: 10,
    statKey: "multiCaptures.triple",
    rewardXp: 800,
    rewardCoins: 400,
  },
  {
    title: "Capture 100 pieces",
    type: "reach",
    goal: 100,
    statKey: "totalCaptures",
    rewardXp: 1000,
    rewardCoins: 500,
  },
  {
    title: "Reach level 10",
    type: "reach",
    goal: 10,
    statKey: "level",
    rewardXp: 1000,
    rewardCoins: 500,
  },
  {
    title: "Complete 30 daily missions",
    type: "reach",
    goal: 30,
    statKey: "stats.dailyMissionsCompleted",
    rewardXp: 1200,
    rewardCoins: 600,
  },
  {
    title: "Win 10 games in a row",
    type: "reach",
    goal: 10,
    statKey: "winStreakMax",
    rewardXp: 1500,
    rewardCoins: 700,
  },
  {
    title: "Play for 7 consecutive days",
    type: "reach",
    goal: 7,
    statKey: "dailyLoginStreak",
    rewardXp: 1500,
    rewardCoins: 750,
  },
  {
    title: "Beat a VIP player",
    type: "reach",
    goal: 1,
    statKey: "defeatedVipPlayer",
    rewardXp: 1000,
    rewardCoins: 500,
  },
]);
console.log("Missions inserted");
process.exit();
